/* prettier-ignore-start */
/* eslint-disable */
// @ts-nocheck
// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

import { createFileRoute, createRootRoute } from '@tanstack/react-router'

import { Route as rootRoute } from './routes/__root'
import { Route as IndexImport } from './routes/index'

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as never)

export interface FileRoutesByPath {
  '/': {
    id: '/'
    path: '/'
    fullPath: '/'
    preLoaderRoute: typeof IndexImport
    parentRoute: typeof rootRoute
  }
}

export const routeTree = rootRoute.addChildren({ IndexRoute })
