/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TasksIndexRouteImport } from './routes/tasks.index'
import { Route as InboxIndexRouteImport } from './routes/inbox.index'
import { Route as ChatIndexRouteImport } from './routes/chat.index'
import { Route as TasksNewRouteImport } from './routes/tasks.new'
import { Route as TasksIdRouteImport } from './routes/tasks.$id'
import { Route as InboxIdRouteImport } from './routes/inbox.$id'
import { Route as ChatNewRouteImport } from './routes/chat.new'
import { Route as ChatIdRouteImport } from './routes/chat.$id'

const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TasksIndexRoute = TasksIndexRouteImport.update({
  id: '/tasks/',
  path: '/tasks/',
  getParentRoute: () => rootRouteImport,
} as any)
const InboxIndexRoute = InboxIndexRouteImport.update({
  id: '/inbox/',
  path: '/inbox/',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatIndexRoute = ChatIndexRouteImport.update({
  id: '/chat/',
  path: '/chat/',
  getParentRoute: () => rootRouteImport,
} as any)
const TasksNewRoute = TasksNewRouteImport.update({
  id: '/tasks/new',
  path: '/tasks/new',
  getParentRoute: () => rootRouteImport,
} as any)
const TasksIdRoute = TasksIdRouteImport.update({
  id: '/tasks/$id',
  path: '/tasks/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const InboxIdRoute = InboxIdRouteImport.update({
  id: '/inbox/$id',
  path: '/inbox/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatNewRoute = ChatNewRouteImport.update({
  id: '/chat/new',
  path: '/chat/new',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatIdRoute = ChatIdRouteImport.update({
  id: '/chat/$id',
  path: '/chat/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/settings': typeof SettingsRoute
  '/chat/$id': typeof ChatIdRoute
  '/chat/new': typeof ChatNewRoute
  '/inbox/$id': typeof InboxIdRoute
  '/tasks/$id': typeof TasksIdRoute
  '/tasks/new': typeof TasksNewRoute
  '/chat/': typeof ChatIndexRoute
  '/inbox/': typeof InboxIndexRoute
  '/tasks/': typeof TasksIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/settings': typeof SettingsRoute
  '/chat/$id': typeof ChatIdRoute
  '/chat/new': typeof ChatNewRoute
  '/inbox/$id': typeof InboxIdRoute
  '/tasks/$id': typeof TasksIdRoute
  '/tasks/new': typeof TasksNewRoute
  '/chat': typeof ChatIndexRoute
  '/inbox': typeof InboxIndexRoute
  '/tasks': typeof TasksIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/settings': typeof SettingsRoute
  '/chat/$id': typeof ChatIdRoute
  '/chat/new': typeof ChatNewRoute
  '/inbox/$id': typeof InboxIdRoute
  '/tasks/$id': typeof TasksIdRoute
  '/tasks/new': typeof TasksNewRoute
  '/chat/': typeof ChatIndexRoute
  '/inbox/': typeof InboxIndexRoute
  '/tasks/': typeof TasksIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/settings'
    | '/chat/$id'
    | '/chat/new'
    | '/inbox/$id'
    | '/tasks/$id'
    | '/tasks/new'
    | '/chat/'
    | '/inbox/'
    | '/tasks/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/settings'
    | '/chat/$id'
    | '/chat/new'
    | '/inbox/$id'
    | '/tasks/$id'
    | '/tasks/new'
    | '/chat'
    | '/inbox'
    | '/tasks'
  id:
    | '__root__'
    | '/'
    | '/settings'
    | '/chat/$id'
    | '/chat/new'
    | '/inbox/$id'
    | '/tasks/$id'
    | '/tasks/new'
    | '/chat/'
    | '/inbox/'
    | '/tasks/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SettingsRoute: typeof SettingsRoute
  ChatIdRoute: typeof ChatIdRoute
  ChatNewRoute: typeof ChatNewRoute
  InboxIdRoute: typeof InboxIdRoute
  TasksIdRoute: typeof TasksIdRoute
  TasksNewRoute: typeof TasksNewRoute
  ChatIndexRoute: typeof ChatIndexRoute
  InboxIndexRoute: typeof InboxIndexRoute
  TasksIndexRoute: typeof TasksIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tasks/': {
      id: '/tasks/'
      path: '/tasks'
      fullPath: '/tasks/'
      preLoaderRoute: typeof TasksIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inbox/': {
      id: '/inbox/'
      path: '/inbox'
      fullPath: '/inbox/'
      preLoaderRoute: typeof InboxIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chat/': {
      id: '/chat/'
      path: '/chat'
      fullPath: '/chat/'
      preLoaderRoute: typeof ChatIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tasks/new': {
      id: '/tasks/new'
      path: '/tasks/new'
      fullPath: '/tasks/new'
      preLoaderRoute: typeof TasksNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tasks/$id': {
      id: '/tasks/$id'
      path: '/tasks/$id'
      fullPath: '/tasks/$id'
      preLoaderRoute: typeof TasksIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inbox/$id': {
      id: '/inbox/$id'
      path: '/inbox/$id'
      fullPath: '/inbox/$id'
      preLoaderRoute: typeof InboxIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chat/new': {
      id: '/chat/new'
      path: '/chat/new'
      fullPath: '/chat/new'
      preLoaderRoute: typeof ChatNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chat/$id': {
      id: '/chat/$id'
      path: '/chat/$id'
      fullPath: '/chat/$id'
      preLoaderRoute: typeof ChatIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SettingsRoute: SettingsRoute,
  ChatIdRoute: ChatIdRoute,
  ChatNewRoute: ChatNewRoute,
  InboxIdRoute: InboxIdRoute,
  TasksIdRoute: TasksIdRoute,
  TasksNewRoute: TasksNewRoute,
  ChatIndexRoute: ChatIndexRoute,
  InboxIndexRoute: InboxIndexRoute,
  TasksIndexRoute: TasksIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
